name: 'DF'
on:
  workflow_dispatch:
jobs:
  DF:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/galacticusorg/buildenv:latest
      options: --privileged
    steps:
      - name: Profile
        run: df -h
      - name: AutoRemove
        run: |
          apt autoremove
          apt list --installed
      - name: Measure
        run: |
          du -sh /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
      - name: Profile
        run: df -h
